---
title: "Roll your own"
---

If we have time, we can make our own formats using format functions.

One trick is that custom-format functions need to be kept in a package

Luckily, Hadley pubished his book on making packages, so we'll use it here.

Here's the repository - you may want to clone.

If you just want to install the package:

```{r eval=FALSE}
install_github("ijlyttle/user2016docdemo")
```

Our custom formats:

* `html_doc_0` simple passthrough to `rmarkdown::html_document()`
* `html_doc_1` changes the default on `code_folding` to `show`
  - add `css: h1_font.css` to yml
* `html_doc_2` adds css to make an improvement to the title font
* `html_doc_3` adds css generated using http://bootstrap-live-customizer.com/
* `html_doc_4` leave this one for later

## Question 

There is something I am not doing right in including the css so that it gets copied to the `site_lib`. Instead, there remains a link in the html to a path on my computer. I need to figure out how to do this properly.
